# Site
title: QuantumBenchmarkZoo
description: Documentation for quantum benchmarks
baseurl: /
permalink: /:title

# Repository
git:
  repository_url: https://github.com/v-gilbert/quantumbenchmarkzoo

# Navigation
nav:
  Zoo:
    - text: Presentation
      page-id: presentation
      url: /
      available: true
    - text: Acknowledgments
      page-id: acknowledgments
      url: /content/the-zoo/acknowedgments
      available: true
    - text: Taxonomy
      page-id: taxonomy
      url: /content/the-zoo/taxonomy
      available: true
  FOM:
    - text: Distance
      page-id: distance-measure
      url: /content/figure-of-merit/distances
      available: true
    - text: Application FOM
      page-id: application-fom
      url: /content/figure-of-merit/application-fom
      available: true
  Protocols:
    - text: Randomized Benchmarking
      url: /content/protocols/randomized/index
      available: true
    - text: Application Benchmarking
      url: /content/protocols/application/index
      available: true
    - text: Quantum Supremacy
      url: /content/protocols/supremacy/index
      available: true
  Users:
    - text: Installation
      url: /installation
      available: true
    - text: Getting started
      url: /start
      available: true
    - text: User management
      url: /user-management
      available: true
    - text: Configuration
      url: /configuration
      available: true
    - text: Targeting players
      url: /targeting
      available: true
    - text: Backup and restore
      url: /backup-and-restore
      available: true
    - text: Reset to defaults
      url: /reset
      available: true
    - text: Tips and tricks
      url: /tips-and-tricks
      available: true
    - text: Third-party modules
      url: /third-party-modules
      available: true
  Developers:
    - text: SVN version
      url: /svn-version
      available: true
    - text: ULX module
      url: /ulx-module
      available: true
    - text: Hooks and functions
      url: /hooks-and-functions
    - text: Custom module
      url: /custom-module
    - text: Custom command
      url: /custom-command
    - text: Custom keyword
      url: /custom-keyword
    - text: Custom XGUI tab
      url: /custom-xgui-tab
  Resources:
    - text: ULX commands
      url: /ulx-commands
      available: true
  Pricing:
    - text: Hardware Access
      url: /content/pricing/index
      available: true


# application protocols
application-protocols:
  - text: Q-Score protocol
    page-id: q-score-protocol
    url: /content/protocols/application/q-score


# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Build
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
exclude: ["README.md"]

# Bibliography
scholar:
  style: apa
  locale: en

  sort_by: none
  order: ascending

  group_by: none
  group_order: ascending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: ""

  replace_strings: true
  join_strings:    true

  use_raw_bibtex_entry: false

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details