# Site
title: QuantumBenchmarkZoo
description: Documentation for quantum benchmarks
baseurl: /
permalink: /:title

# Repository
git:
  repository_url: https://github.com/v-gilbert/quantumbenchmarkzoo

# Navigation
nav:
  Zoo:
    - text: Presentation
      page-id: presentation
      url: /
      available: true
    - text: Acknowledgments
      page-id: acknowledgments
      url: /content/the-zoo/acknowledgments
      available: true
    - text: Taxonomy
      page-id: taxonomy
      url: /content/the-zoo/taxonomy
      available: true
  FOM:
    - text: Fidelities and errors
      page-id: fidelities-errors
      url: /content/figure-of-merit/fidelities-errors
      available: true
    - text: Application FOM
      page-id: application-fom
      url: /content/figure-of-merit/application-fom
      available: true
  Protocols:
    - text: Randomized Benchmarks
      page-id: randomized-benchmarks
      url: /content/protocols/randomized/protocols
      available: true
    - text: Application Benchmarks
      page-id: application-benchmarks
      url: /content/protocols/application/protocols  
      available: true
    - text: Quantum Supremacy
      page-id: supremacy-benchmarks
      url: /content/protocols/supremacy/protocols
      available: true
  Pricing:
    - text: Hardware Access
      url: /content/pricing/hardware-access
      available: true

# Randomized protocols
randomized-protocols:
  sampling-problems:
    - text: HOG problem
      page-id: hog-problem
      url: /content/protocols/randomized/hog-problem
  volume-benchmarks:
    - text: Quantum Volume
      page-id: quantum-volume
      url: /content/protocols/randomized/quantum-volume
    - text: CLOPS
      page-id: clops
      url: /content/protocols/randomized/clops

# Application protocols
application-protocols:
  - text: Q-Score protocol
    page-id: q-score-protocol
    url: /content/protocols/application/q-score

# Supremacy protocols
supremacy-protocols:
  - text: Random circuit sampling
    page-id: random-circuit-sampling
    url: /content/protocols/supremacy/random-circuit-sampling
  - text: Boson sampling 
    page-id: boson-sampling
    url: /content/protocols/supremacy/boson-sampling
  - text: Quantum simulation
    page-id: quantum-simulation
    url: /content/protocols/supremacy/quantum-simulation
  
# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Build
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
exclude: ["README.md"]

# Bibliography
scholar:
  style: ieee-with-url
  locale: en

  sort_by: none
  order: ascending

  group_by: none
  group_order: ascending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: ""

  replace_strings: true
  join_strings:    true

  use_raw_bibtex_entry: false

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details