# Site
title: QuantumBenchmarkZoo
description: Documentation for quantum benchmarks
baseurl: /
permalink: /:title

# Repository
git:
  repository_url: https://github.com/v-gilbert/quantumbenchmarkzoo

# Navigation
nav:
  Zoo:
    - text: Presentation
      page-id: presentation
      url: /
      available: true
    - text: Acknowledgments
      page-id: acknowledgments
      url: /content/the-zoo/acknowledgments
      available: true
    - text: Terminology
      page-id: terminology
      url: /content/the-zoo/terminology
      available: true
  FOM:
    - text: Component-level FOM
      page-id: fidelities-errors
      url: /content/figure-of-merit/component-level-fom
      available: false
    - text: Fidelities and errors
      page-id: fidelities-errors
      url: /content/figure-of-merit/fidelities-errors
      available: true
    - text: Application-level FOM
      page-id: application-fom
      url: /content/figure-of-merit/application-fom
      available: true
  Component-level:
    - text: Qubit coherence
      page-id: qubit-coherence
      url: /content/component-level-benchmark/qubit-coherence
      available: false
  System-level:
    - text: Randomized benchmarking
      page-id: randomized-benchmarks
      url: /content/system-level-benchmark/randomized/protocols
      available: true
    - text: Supremacy experiments
      page-id: supremacy-benchmarks
      url: /content/system-level-benchmark/supremacy/protocols
      available: true
    - text: Others
      page-id: others
      url: /content/system-level-benchmark/others/protocols
      available: true
  Application-level:
    - text: Protocols
      page-id: application-benchmarks
      url: /content/application-level-benchmark/protocols  
      available: true
    - text: Frameworks
      page-id: application-benchmarks
      url: /content/application-level-benchmark/frameworks  
      available: false
    - text: Datasets
      page-id: application-benchmarks
      url: /content/application-level-benchmark/datasets  
      available: false
  Ftqc:
    - text: FTQC Experiments
      page-id: ftqc
      url: /content/ftqc/experiments
      available: true
    - text: FTQC Resource Estimation
      page-id: ftqc-resource-estimation
      url: /content/ftqc/resource-estimation
      available: false
  Business-informations:
    - text: Hardware Access Pricing
      url: /content/business-info/hardware-access
      available: true
    - text: Roadmaps
      url: /content/business-info/roadmaps
      available: true

# Randomized protocols
randomized-protocols:
  volume-benchmarks:
    - text: Quantum Volume
      page-id: quantum-volume
      url: /content/system-level-benchmark/quantum-volume
    - text: CLOPS
      page-id: clops
      url: /content/system-level-benchmark/clops

# Application protocols
application-protocols:
  - text: Q-Score protocol
    page-id: q-score-protocol
    url: /content/application-level-benchmark/q-score
  - text: Volumetric-benchmark
    page-id: volumetric-benchmark
    url: /content/application-level-benchmark/volumetric-benchmark
  - text: algorithmic-qubit
    page-id: algorithmic-qubit
    url: /content/application-level-benchmark/algorithmic-qubit
  - text: qbas
    page-id: qbas
    url: /content/application-level-benchmark/qbas
    
# Supremacy protocols
supremacy-protocols:
  - text: Random circuit sampling
    page-id: random-circuit-sampling
    url: /content/system-level-benchmark/supremacy/random-circuit-sampling
  - text: Boson sampling 
    page-id: boson-sampling
    url: /content/system-level-benchmark/supremacy/boson-sampling
  - text: Quantum simulation
    page-id: quantum-simulation
    url: /content/system-level-benchmark/supremacy/quantum-simulation
  
# Other system level protocols
other-system-level-protocols:
  - text: Quantum volume
    page-id: quantum-volume
    url: /content/system-level-benchmark/others/quantum-volume
  - text: clops
    page-id: clops
    url: /content/system-level-benchmark/others/clops
  - text: ques
    page-id: ques
    url: /content/system-level-benchmark/others/ques



# Fault-tolerant error correcting codes implementations
# Fault-tolerant Implementation:
#  - text: Correction codes
#    page-id: qecc
#    url: /content/ftqc/qecc

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Build
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
exclude: ["README.md"]

# Bibliography
scholar:
  style: ieee-with-url
  locale: en

  sort_by: none
  order: ascending

  group_by: none
  group_order: ascending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: ""

  replace_strings: true
  join_strings:    true

  use_raw_bibtex_entry: false

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

# last modified
#last-modified-at:
#  date-format: '%d-%b-%y'