# Site
title: QuantumBenchmarkZoo
description: Documentation for quantum benchmarks
permalink: /:title
url: https://quantumbenchmarkzoo.org
baseurl: ""

# Repository
git:
  repository_url: https://github.com/v-gilbert/quantumbenchmarkzoo

# Navigation
nav:
  Zoo:
    - text: Presentation
      page-id: presentation
      url: /
      available: true
    - text: Acknowledgments
      page-id: acknowledgments
      url: /content/the-zoo/acknowledgments
      available: true
    - text: Contact us
      page-id: contact
      url: /content/the-zoo/contact
      available: true
    - text: Terminology
      page-id: terminology
      url: /content/the-zoo/terminology
      available: true
  FOM:
    - text: Component-level FOM
      page-id: component-level-fom
      url: /content/figure-of-merit/component-level-fom
      available: false
    - text: Fidelities and errors
      page-id: fidelities-errors
      url: /content/figure-of-merit/fidelities-errors
      available: true
    - text: Application-level FOM
      page-id: application-fom
      url: /content/figure-of-merit/application-fom
      available: true
  Component-level:
    - text: Qubit coherence
      page-id: qubit-coherence
      url: /content/component-level-benchmark/qubit-coherence
      available: false
  System-level:
    - text: Randomized benchmarking
      page-id: randomized-benchmarks
      url: /content/system-level-benchmark/randomized-benchmarking/
      available: true
    - text: Supremacy experiments
      page-id: supremacy-benchmarks
      url: /content/system-level-benchmark/supremacy/
      available: true
    - text: Others
      page-id: others
      url: /content/system-level-benchmark/others/
      available: true
  Application-level:
    - text: Protocols
      page-id: application-benchmarks
      url: /content/application-level-benchmark/protocols/
      available: true
    - text: Aggregated scores
      page-id: aggregated-scores
      url: /content/application-level-benchmark/aggregated-scores
      available: true
    - text: Frameworks
      page-id: application-benchmarks
      url: /content/application-level-benchmark/frameworks  
      available: false
  Multi-level:
    - text: Methodologies
      page-id: multi-level-methodologies
      url: /content/multi-level-benchmark/methodology/
      available: true
  benchmarking-datasets:
    - text: Problem libraries
      page-id: problem-libraries
      url: /content/benchmarking-datasets/problem-libraries
      available: true
    - text: Quantum datasets
      page-id: quantum-datasets
      url: /content/benchmarking-datasets/quantum-datasets
      available: true
  Ftqc:
    - text: QECC Experiments
      page-id: qecc
      url: /content/ftqc/experiments
      available: true
    - text: FTQC Resource Estimation
      page-id: ftqc-resource-estimation
      url: /content/ftqc/resource-estimation
      available: false
  Business-informations:
    - text: Hardware Access Pricing
      page-id: hardware-access
      url: /content/business-info/hardware-access
      available: true
    - text: Roadmaps
      page-id: roadmaps
      url: /content/business-info/roadmaps
      available: true
    - text: Benchmarking initiatives
      page-id: benchmarking-initiatives
      url: /content/business-info/other-benchmarking-initiative
      available: true

# Randomized protocols
randomized-benchmarking-protocols:
  - text: Single-qubit Clifford Randomized Benchmarking
    page-id: single-qubit-CRB
    url: /content/system-level-benchmark/randomized-benchmarking/single-qubit-CRB
  - text: Multi-qubit Clifford Randomized Benchmarking
    page-id: multi-qubit-CRB
    url: /content/system-level-benchmark/randomized-benchmarking/multi-qubit-CRB
  - text: Direct Randomized Benchmarking
    page-id: DRB
    url: /content/system-level-benchmark/randomized-benchmarking/DRB
  - text: Binary Randomized Benchmarking
    page-id: BRB
    url: /content/system-level-benchmark/randomized-benchmarking/BRB
  - text: Mirror Randomized Benchmarking
    page-id: MRB
    url: /content/system-level-benchmark/randomized-benchmarking/MRB
  - text: Dihedral Randomized Benchmarking
    page-id: dihedral-RB
    url: /content/system-level-benchmark/randomized-benchmarking/dihedral-RB
  - text: Simultaneous Randomized Benchmarking
    page-id: SRB
    url: /content/system-level-benchmark/randomized-benchmarking/SRB
  - text: Interleaved Randomized Benchmarking
    page-id: IRB
    url: /content/system-level-benchmark/randomized-benchmarking/IRB
  - text: Cycle Benchmarking
    page-id: CB
    url: /content/system-level-benchmark/randomized-benchmarking/cycle-RB
  - text: Correlated Randomized Benchmarking
    page-id: correlated-RB
    url: /content/system-level-benchmark/randomized-benchmarking/correlated-RB   
  - text: Error per layered gate
    page-id: eplg
    url: /content/system-level-benchmark/randomized-benchmarking/eplg


# Application protocols
application-protocols:
  - text: Q-Score protocol
    page-id: q-score-protocol
    url: /content/application-level-benchmark/protocols/q-score
  - text: LR-QAOA protocol
    page-id: lr-qaoa-protocol
    url: /content/application-level-benchmark/protocols/lr-qaoa
  - text: algorithmic-qubit
    page-id: algorithmic-qubit
    url: /content/application-level-benchmark/protocols/algorithmic-qubit
  - text: qbas
    page-id: qbas
    url: /content/application-level-benchmark/protocols/qbas
    
# Supremacy protocols
supremacy-protocols:
  - text: Random circuit sampling
    page-id: random-circuit-sampling
    url: /content/system-level-benchmark/supremacy/random-circuit-sampling
  - text: Boson sampling 
    page-id: boson-sampling
    url: /content/system-level-benchmark/supremacy/boson-sampling
  - text: Quantum simulation
    page-id: quantum-simulation
    url: /content/system-level-benchmark/supremacy/quantum-simulation
  
# Other system level protocols
other-system-level-protocols:
  - text: Quantum volume
    page-id: quantum-volume
    url: /content/system-level-benchmark/others/quantum-volume
  - text: clops
    page-id: clops
    url: /content/system-level-benchmark/others/clops
  - text: Quantum linpack
    page-id: quantum-linpack
    url: /content/system-level-benchmark/others/quantum-linpack
  - text: ques
    page-id: ques
    url: /content/system-level-benchmark/others/ques
  - text: rQOPS
    page-id: rqops
    url: /content/system-level-benchmark/others/rqops

multi-level-methodologies:
  - text: MNR
    page-id: MNR
    url: /content/multi-level-benchmark/methodology/MNR

# Fault-tolerant error correcting codes implementations
# Fault-tolerant Implementation:
#  - text: Correction codes
#    page-id: qecc
#    url: /content/ftqc/qecc

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Build
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
exclude: ["README.md", "doc"]

# Bibliography
scholar:
  style: ieee-with-url
  locale: en

  sort_by: none
  order: ascending

  group_by: none
  group_order: ascending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: ""

  replace_strings: true
  join_strings:    true

  use_raw_bibtex_entry: false

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

plugins:
  - jekyll-sitemap

# last modified
#last-modified-at:
#  date-format: '%d-%b-%y'